// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TANC7jIESx3k8VXeGFWDuBHEzb4eu94',
    appId: '1:1008819711665:android:c8d7cc6543eca81de6bc90',
    messagingSenderId: '1008819711665',
    projectId: 'product-app-course-787ab',
    storageBucket: 'product-app-course-787ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UkPZRU1gyAu-AsQVvWwwp_ER39qE8FU',
    appId: '1:1008819711665:ios:74f7347b2336274de6bc90',
    messagingSenderId: '1008819711665',
    projectId: 'product-app-course-787ab',
    storageBucket: 'product-app-course-787ab.appspot.com',
    iosClientId: '1008819711665-h51r8humjmhjit61s7mbdm1s3bqvs07j.apps.googleusercontent.com',
    iosBundleId: 'com.gadgetoflife.productapp',
  );
}
